name: 'generate_embeddings'
on: # run on main branch changes
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/embeddings-generator@v0.0.5 # Find the latest version in the Marketplace
        with:
          supabase-url: 'https://ctmbbtlnsdevifehxbcu.supabase.co'
          supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          openai-key: ${{ secrets.OPENAI_KEY }}
          embedding-model: 'text-embedding-3-small' # optional; defaults to text-embedding-ada-002
          docs-root-path: 'docs' # the path to the root of your md(x) files